# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWIFTYLIBMINE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFTYLIBMINE

    pod 'Alamofire'

  target 'SWIFTYLIBMINETests' do
    # Pods for testing
  end

end

target 'SWIFTYLIBMINEExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWIFTYLIBMINEExample

end
